### PR TITLE
Makes the display of maps in the detail view GDPR compliant

### PR DESCRIPTION
**Pull request by Erftralle**
This pull request is a proposal to fix issue #47 . See #47 for more information.

### CODE REVIEW

**Comment by MrMusic** [comment]
Thank you for the implementation. It works very well!

I am considering whether there is an easy way (an override?) to always display the map (as before).
Possibly are there cases where the 2Click solution is not necessary, e.g. in certain countries or in an intranet?

**Comment by Erftralle** [comment]
Moving the call of the Google Maps API from the view to the template file would make it possible to re-establish the current/old behaviour with an template override.

Another possibility would be to introduce a new configuration parameter. Only slightly more complex, but easier for most users.

What is your opinion?

**Comment by MrMusic** [comment]
>Moving the call of the Google Maps API from the view to the template file would make it possible to re-establish the current/old behaviour with an template override.

Yes, it is possible with a template override.
I inserted the following code into the template file after `<div id="jg_geomap">` and it works.
```
<?php   if($this->_mainframe->getUserState('joom.geomap.show', 0) === 0):
          $this->_doc->addScript('http'.(JUri::getInstance()->isSSL() ? 's' : '').'://maps.google.com/maps/api/js?sensor=false'.(!empty($apikey) ? '&amp;key='.$apikey : ''));
          JFactory::getApplication()->setUserState('joom.geomap.show', 1);
        endif; ?>
```

>Another possibility would be to introduce a new configuration parameter

Before we introduce a new configuration parameter we should wait for the user feedback.

I have tested this item ✅ successfully. Thank you very much!

**Comment by Erftralle** [comment]
Thanks for your feedback.

> Before we introduce a new configuration parameter we should wait for the user feedback.

OK, I agree.

> I inserted the following code into the template file after `<div id="jg_geomap">` and it works.

Unfortunately your suggested code does not work. First of all it is logically wrong since it loads the Google Maps API and sets the user state although the user hasn't pressed the button to show the map yet. Besides the variable `$apikey` is not declared in that scope.

Please could you test my code changes and give feedback again. Thanks.

**Comment by MrMusic** [comment]
Yes, I have overlooked the `$apikey`.

Thanks for your change.
So the code is better and the function can easily be changed via override.

Thank you very much.

**Pull request merged**
