### PR TITLE
Fix use the general 'File comment' for the ReplaceWithMetadata feature

### PR DESCRIPTION
**Pull request by MrMusic**
A fix to use the 'Exif comment' for the ReplaceWithMetadata feature.

### CODE REVIEW

**Comment by Erftralle** [comment]
This doesn't work for me. As far as I read there is no item with tag attribute 'COMMENT'  **in the EXIF data**, but there is an item with tag attribute 'UserComment'.

The exif_read_data documentation says:

 > When an Exif header contains a Copyright note, this itself can contain two values. As the solution is inconsistent in the Exif 2.10 standard, the COMPUTED section will return both entries Copyright.Photographer and Copyright.Editor while the IFD0 sections contains the byte array with the NULL character that splits both entries. Or just the first entry if the datatype was wrong (normal behaviour of Exif). The COMPUTED will also contain the entry Copyright which is either the original copyright string, or a comma separated list of the photo and editor copyright.
>
> The tag UserComment has the same problem as the Copyright tag. It can store two values. First the encoding used, and second the value itself. If so the IFD section only contains the encoding or a byte array. The COMPUTED section will store both in the entries UserCommentEncoding and UserComment. The entry UserComment is available in both cases so it should be used in preference to the value in IFD0 section. 

See also my comment [here](https://github.com/JoomGalleryfriends/JoomGallery/pull/13#issuecomment-551113015).

**Comment by MrMusic** [comment]
>This doesn't work for me. As far as I read there is no item with tag attribute 'COMMENT' in the EXIF data, but there is an item with tag attribute 'UserComment'.

Yes, there are two different problems. 
This pull request should be used to use the 'file comment'. This is different to the Exif "UserComment".
For the distinction I gave the 'file comment' now the id = "99999".

And yes, the problem with reading the exif "UserComment" I have also.
After I saved a comment with Exiftool, the php function gives me the leading 'ASCII...'.
Maybe we should not use this exif tag?

**Comment by 19leunam93** [comment]
To avoid confusion:
There exist two ways of storing comments in image-file:
- exif UserComment (Exif.Photo.UserComment)
- jpeg header comment

What you are adding in that pull request MrMusic is the ability to use the jpeg header comment in the ReplaceWithMetadata feature.

I have created another pull request #20 to fix the usage of the exif UserComment.

Here the two ways of storing comments are compaired:
https://www.scootersoftware.com/vbulletin/forum/beyond-compare-4-discussion/general/14227-jpeg-exif-comments-vs-jpeg-header-comments

In my opinion, the usage of the exif UserComment has to be used and the the jpeg header comment dont, because:
- exif metadata can be used for both png and jpeg files
- jpeg header comment is only supported by jpeg files
- dealing with exif metadata is supported by the most image programs, where only a few are able to deal with jpeg header comments 
- exif pilot and windows explorer for example arent able to edit jpeg header comments but can edit exif UserComment

**Comment by MrMusic** [comment]
Thank you for your hint.

>In my opinion, the usage of the exif UserComment has to be used and the the jpeg header comment dont...

But i would like to keep the jpeg header comment too.
For example, the popular IrfanView (which exists since 1996) can directly edit the jpeg comment but not the exif UserComment.

**Comment by 19leunam93** [comment]
hmmm... also XnView is only able to edit the jpeg comment but not the exif UserComment!

It semms as if some progams are supporting jpeg comment and other exif UserComment, but not both...

**Comment by Erftralle** [comment]
> To avoid confusion:
There exist two ways of storing comments in image-file:
>
>    - exif UserComment (Exif.Photo.UserComment)
>   - jpeg header comment
>
> What you are adding in that pull request MrMusic is the ability to use the jpeg header comment in the ReplaceWithMetadata feature.

Thanks for the clarification, indeed I have been a little bit confused. I was searching for a bug (found one but not the same) which this pull request should be a fix for but this pull request is rather a new feature for the new feature 😄  .

Since I am undecided on whether we should also integrate the JPEG header comment, I leave the decision to you.

If you decide to add it
- you should add the missing new language constants to the language file
- discuss wether or not to integrate the JPEG header comment in the EXIF section of the detail view and wether to make it configurable to display it in the configuration manager.

**Comment by MrMusic** [comment]
Sorry if I have caused confusion. 
I was really only about using of the comment in the new ReplaceWithMetadata feature.

>...integrate the JPEG header comment in the EXIF section of the detail view and wether to make it configurable to display it in the configuration manager.

That would mean bigger changes. One would have to e.g. create a new configuration option because this comment does not belong to Exif nor IPTC data, adds a new array to joomgalleryconfig and so on.
I will close the pull request now and start without the JPEG comment.
If there is a request from the community, we can start the topic again.

**Pull request closed without merging**
