### PR TITLE
Rotate images

### PR DESCRIPTION
**Pull request by MrMusic**
DE:
Nachdem es bereits mit https://github.com/JoomGallery/JoomGallery/pull/110 und https://github.com/JoomGallery/JoomGallery/pull/168 Vorschläge für eine automatische Bilddrehung gab, hier nun eine überarbeitete Version. Diese Version kommt ohne eine externe Library (PEL) aus.
Bei Verwendung des Bildbearbeiters GD2 werden bei der Drehung die Exif- und IPTC-Daten gelöscht.
Bei Verwendung von Imagemagick bleiben bei der Drehung die Exif- und IPTC-Daten erhalten.
Im Konfigurations-Manager kann eingestellt werden, ob neben Thumbnail und Detailbild auch das Originalbild gedreht werden soll. So ist es möglich das Originalbild auch zu drehen oder unverändert zu lassen.
Neben der automatischen Bilddrehung anhand der Exif-Orientierung ist auch die "manuelle" Drehung mit Hilfe der Stapel-Bearbeitung möglich.

EN:
Since there were already suggestions for an automatic image rotation with https://github.com/JoomGallery/JoomGallery/pull/110 and https://github.com/JoomGallery/JoomGallery/pull/168, here now a revised version. This version does not require an external library (PEL).
When using the image processor GD2, the rotation erases the Exif and IPTC data.
When using Imagemagick, the rotation preserves the Exif and IPTC data.
In the Configuration Manager can be set whether in addition to thumbnail and detail image the original image is rotated. So it is possible to rotate the original image or leave it unchanged.
In addition to the automatic image rotation based on the Exif orientation, manual rotation using batch processing is also possible.

### CODE REVIEW

**Comment by Erftralle** [comment]
I've only done a few tests so far, but I'd like to give you some feedback now.

- In my opinion the default value of the two new options (jg_fe_exif_rotation, jg_be_exif_rotation) should be 0, at least for an update of the JoomGallery. People just updating their JoomGallery should not be surprised. In my opinion one option for front and back end would be enough or is there a reason to act different in front and back end?
  
- In upload.php we have 6 times the same  code:

`        // Begin rotation
        if($this->_site)
        {
          $autorotate_images = $this->_config->get('jg_fe_exif_rotation');
        }
        ...
        ...
`
It would make sense to me to make a function out of it or maybe move this code into the JoomUpload::resizeImage function.

- In the Java Upload you load images from the FTP Upload directory

```
          // Copy original image into original folder
          $return = JFile::copy($this->_ambit->get('ftp_path').$subdirectory.$origfilename,
                                $this->_ambit->getImg('orig_path', $newfilename, null, $this->catid));
```
- In the Java Upload, when using the option to delete the originals after upload, the Java applet does the resizing itself and only the resized image is uploaded.  So in the backend only the thumb is created and rotated while the detail image is not.  Besides the Java Applet has it's own possibility to rotate the images before they are uploaded. Unfortunately the applet does not update the EXIF orientation when rotation is done. This might cause a double rotation (first the applet and then in the server code).

- When using the batch to rotate images in the backend (edit images form) images will be rotated although the check box 'Rotate' is not checked. Just a single image can't be rotated at all. In my opinion the edit images form is the wrong place to do the rotation. Here only database fields are modified. In my opinion it would be better to have a "Rotate" button in the image manager to open a separate form (similar to the move images form but implemented with Joomla forms).

- When using the batch to rotate images the images are "just rotated". That means that the sizes after the rotation are not according to the general settings for image processing in the configuration manager. What do think of that?

- When using ImageMagick for image processing and rotation the EXIF data stays in the file but the Orientation data is not modified during the rotation. This could cause further problems, what do you thing?
There is an option available to rotate images with ImageMagick while updating the EXIF information (see option -auto-orient).

**Comment by MrMusic** [comment]
Thank your for your feedback.

>In my opinion the default value of the two new options (jg_fe_exif_rotation, jg_be_exif_rotation) should be 0, at least for an update of the JoomGallery. People just updating their JoomGallery should not be surprised. 

I think most users expect this feature is enabled by default. At least for a new installation.
A problem should actually only occur if the images were rotated before the upload and the orientation tag was not modified.
Would it be useful for a new installation and make the update different default settings?


>In my opinion one option for front and back end would be enough or is there a reason to act different in front and back end?

Ok, i changed to one option and moved to image processing tab.


>In upload.php we have 6 times the same code...

Yes, you're right. I moved the code in the JoomUpload::resizeImage function.


>In the Java Upload...

For me, the Java Upload is 'dead'. I think we should removed the exif rotation in Java Upload completely.


>When using the batch to rotate images...

I'm not sure what the best is.
This would mean an 'Rotation' button in Image Manager near the Move button?
Currently it is possibility to move/copy images even in the "Batch" window.
It might be an advantage to have all functions for image editing in one window?


>When using the batch to rotate images the images are "just rotated"...

For the detailed images it makes no difference because this on the max width or height are reduced.
For the thumbnails it can mean that the height of the portrait images changes. I'm not sure if the user wants an automatic resizing here. If a resizing is desired, he can do this relatively easily with a "Recreate". Actually, the manual rotation should only rarely be necessary.

 
>When using ImageMagick for image processing and rotation...

Thanks for the hint. I had overlooked that the option can update the Orientation data.


I hope the new version is now a little better.

Another Question:
When rotating the original image the quality parameter from detailed image is used.
Should whe create a new quality parameter for this in configuration manager and use it for watermarked images too?

**Comment by Erftralle** [comment]
> I hope the new version is now a little better.

After your changes, the rotation does not work anymore during the upload.

**Comment by MrMusic** [comment]
Sorry, i forgot to upload a file.

**Comment by Erftralle** [comment]
Thank you.

> Sorry, i forgot to upload a file.

Uups, may I ask how this happened? Don't you work directly on this branch?
If yes, all changes you do on an already created pull request should automatically update this pull request when comitting and pushing this branch.

> Would it be useful for a new installation and make the update different default settings?

I could live with this compromise, although I would prefer if the parameter 'jg_upload_exif_rotation' would also be 0 on a new installation.

> Ok, i changed to one option and moved to image processing tab.

Thank you.

> Yes, you're right. I moved the code in the JoomUpload::resizeImage function.

That's much better, thank you.
What do you think of the following suggestions to improove and simplify the code in the file **upload.php**:
- In line 411, 778, 1120, 1642 handing over the two default parameters is not neccessary any more
- In the function **uploadFTP()** remove line 1322-1331 (Copy original image into original folder), line 1344-1356 (Delete file from ftp path if needed), change line 1334 to the original code and move lines 2108-2126 (Rotate original image if needed) in the function **resizeImage()** to the end of the function just before the `return true;` in line 2228.

> For me, the Java Upload is 'dead'. I think we should removed the exif rotation in Java Upload completely.

Ok, I could live with that too. 

> I'm not sure what the best is.
This would mean an 'Rotation' button in Image Manager near the Move button?
Currently it is possibility to move/copy images even in the "Batch" window.
It might be an advantage to have all functions for image editing in one window?

Moving or copying images to another category means changing an image database field (see above comment), rotation not. It' s more like the 'Recreate' function. 
Besides you did not answer or react on the following statements I made in my comment above:
- Images will be rotated although the check box 'Rotate' is not checked.
- How do you rotate only one image ?

> For the detailed images it makes no difference because this on the max width or height are reduced. For the thumbnails it can mean that the height of the portrait images changes. I'm not sure if the user wants an automatic resizing here. If a resizing is desired, he can do this relatively easily with a "Recreate". Actually, the manual rotation should only rarely be necessary.

Yes, you are right, it does only concern the thumbnails and sure, a 'Recreate' is possible.
I don't no what other users would expect, I only know what I would expect :wink: .

 > Thanks for the hint. I had overlooked that the option can update the Orientation data.

I saw that you changed the code in the file **file.php** (650ff) to

```
       if(!is_null($offsetx) && !is_null($offsety))
        {
          if($angle > 0)
          {
            $commands .= ' -crop "'.$srcHeight.'x'.$srcWidth.'+'.$offsety.'+'.$offsetx.'" +repage';
          }
          else
          {
            $commands .= ' -crop "'.$srcWidth.'x'.$srcHeight.'+'.$offsetx.'+'.$offsety.'" +repage';
          }
        }
        if($angle > 0)
        {
          $commands .= ' -auto-orient';
        }
        // Finally the resize
        $commands  .= ' -resize "'.$destWidth.'x'.$destHeight.'" -quality "'.$dest_qual.'" -unsharp "3.5x1.2+1.0+0.10"';
```
This code does not work for an $angle = 180. Besides this code makes my brain turning round and round because there has been already a change of width and height in line 344 which is now changed back.

Wouldn't it be better to leave it to one change in line 344 and change above code to:
```
        if($angle > 0)
        {
          $commands .= ' -auto-orient';
        }

        if(!is_null($offsetx) && !is_null($offsety))
        {
          $commands .= ' -crop "'.$srcWidth.'x'.$srcHeight.'+'.$offsetx.'+'.$offsety.'" +repage';
        }

        // Finally the resize
        $commands  .= ' -resize "'.$destWidth.'x'.$destHeight.'" -quality "'.$dest_qual.'" -unsharp "3.5x1.2+1.0+0.10"';
```

If I understand the documentation of ImageMagick correctly the conversions are done in the order of the parameters given, that means first rotation, then cropping and at last resizing. That should make the second exchange you did superflous. I did some tests on it that looked quite good, maybe you can check that too.
  
> Another Question:
When rotating the original image the quality parameter from detailed image is used.
Should whe create a new quality parameter for this in configuration manager and use it for watermarked images too?

We should come back to this point later.

**Comment by MrMusic** [comment]
>Uups, may I ask how this happened? Don't you work directly on this branch?...

I work locale with XAMPP. When my locale changes are complete, i move it into the Github Repo.
While this transfer i had overlooked a file.


>In line 411, 778, 1120, 1642 handing over the two default parameters is not neccessary any more

Ok, i removed the two parameters


>I would prefer if the parameter 'jg_upload_exif_rotation' would also be 0 on a new installation.

Ok, i changed the parameter


>In the function uploadFTP() remove line...

Ok, i tried to change it.
But now I have the problem that the files in the ftp folder are "changed" during the upload. For me it looks wrong. In addition, the originals in the original directory are not rotated properly.
What do you think?


>Moving or copying images to another category means...

At the moment i did not change anything about the manual rotation.
For the idea with the own button i have no solution. I hoped you would give me a solution. :wink:


>I saw that you changed the code in the file file.php (650ff) to...

In the old code, when creating square thumbnails with ImageMagick a wrong sector was used. Therefore, I had tried to solve the problem with this code changes.
Of course only with changing the parameter order it is much better. 
Thank you for the hint!

**Comment by Erftralle** [comment]
I have opened a pull request with proposals towards your branch which may resolve all the remaining issues I mentioned above. Have a look to the single commits which explain and show what I have done exactly.

If you are willing to use that code please review and test it  thoroughly. There were a lot of changes overall.

**Comment by MrMusic** [comment]
>I have opened a pull request with proposals towards your branch which may resolve all the remaining issues I mentioned above. Have a look to the single commits which explain and show what I have done exactly.
If you are willing to use that code please review and test it thoroughly. There were a lot of changes overall.

Wow, really a lot of changes!

Only one problem: I believe in line 874 of the file ...models/images.php the comma must be removed.

Otherwise, I have made extensive tests: Various image processor... Various upload methods (except Java upload)...
Everything worked really great.
Wonderful - Thank you so much!

**Comment by Erftralle** [comment]
Thank you very much for the extensive tests.

> Only one problem: I believe in line 874 of the file ...models/images.php the comma must be removed.

Yes, you are right. I have added a commit to my pull request to fix this but as you have allready merged my branch I don't know how you can add this additional commit to your branch.

> Another Question: When rotating the original image the quality parameter from detailed image is used. Should whe create a new quality parameter for this in configuration manager and use it for watermarked images too?  We should come back to this point later.

> We should come back to this point later.

As we have a quality parameter for thumbs and detail images there should be one for the so called originals if they are rotated.

**Comment by MrMusic** [comment]
>Yes, you are right. I have added a commit to my pull request to fix this but as you have allready merged my branch I don't know how you can add this additional commit to your branch.

It is probably necessary to create a new pull request?
But I have already done it.

>As we have a quality parameter for thumbs and detail images there should be one for the so called originals if they are rotated.

The new additional configuration parameter for the quality have i done too.

I noticed a small thing: if the manual rotate in the image manager fails, the error message looks a bit "ugly". What do you think about inserting a additional line break at the end of lines 845, 856 and 894.

**Comment by Erftralle** [comment]
> It is probably necessary to create a new pull request?
But I have already done it.

Probably yes and thank you.

> The new additional configuration parameter for the quality have i done too.

Working fine, thank you :+1: .

During the test I noticed something new. The two new options (jg_originalquality, jg_upload_exif_rotation) are missing in **administrator/components/com_joomgallery/helpers/config.php**.

> I noticed a small thing: if the manual rotate in the image manager fails, the error message looks a bit "ugly". What do you think about inserting a additional line break at the end of lines 845, 856 and 894.

That's a good idea. Would you mind taking over this for me?

**Comment by MrMusic** [comment]
>During the test I noticed something new. The two new options (jg_originalquality, jg_upload_exif_rotation) are missing in administrator/components/com_joomgallery/helpers/config.php.

Thank you. I completely overlooked this file.

>That's a good idea. Would you mind taking over this for me?

Yes, I have inserted the line breaks now.
That was relatively easy ;-)

**Comment by Erftralle** [comment]
I have tested this item :white_check_mark: successfully.

Thank you.

**Comment by MrMusic** [comment]
Thank you very much @Erftralle

**Pull request merged**
