### PR TITLE
Limiting WYSIWYG editor height for image description (frontend and backend)

### PR DESCRIPTION
**Pull request by 19leunam93**
Since pull request #8, there is a WYSIWYG editor in in the upload forms (frontend and backend) for the image description. Most popular editors take up a lot of space, making the upload form larger and more bulky.
This pull request adds a limit of 250px for the height of the most popular editors:
- No editor
- CodeMirror
- TinyMCE
- JCE
- CKE-Editoren (DropEditor, CKEditor)

Are there any other editors, which should get a height limit in the upload forms of JoomGallery?

### CODE REVIEW

**Comment by reilldesign** [comment]
A limitation of the editor window height would be desirable for all editing layouts. As also e.g. with

› Category Manager :: Edit Category
› Image Manager :: Edit Image

**Comment by 19leunam93** [comment]
I agree with that. Limited editor heights are more handy in all of the form-views of JoomGallery.

**Comment by MrMusic** [comment]
I understand that you want the editor's height to be smaller.
But i do not know if this is the right place, especially for the edit forms.
For the popular editors like TinyMCE and JCE, the size can already be set in the respective editor configuration.
This allows the admin to set the size of the editor globally.

**Comment by Erftralle** [comment]
👍 

Just one view is still missing (editimages.xml).

**Comment by Erftralle** [comment]
@MrMusic : Seems we overlapped when commenting 😄 .

> But i do not know if this is the right place, especially for the edit forms.
For the popular editors like TinyMCE and JCE, the size can already be set in the respective editor configuration.

I did not even know these options 😲 . Thanks for the hint. And what about CodeMirror and the CKE editors?

But in the case of 'No editor' (that means using just a textarea element) the height attribute in the XML files for the forms would still be helpfull?

**Comment by 19leunam93** [comment]
Thanks for the hint regarding the possibility to set the heights of some editors in its settings. Now my height limits gets overritten by the editor settings if set...

**Comment by Erftralle** [comment]
I thought again about this proposal. Somehow I find that the **recent commit** of the proposed changes hardly make any sense anymore.

If I understood it correctly, originally we wanted the height of the WYSIWYG editor to be limited for the case of the image description. The reason for that is that in most cases the image description has rather limited length and a huge editor height make the forms cluttered and unwieldy. But in order to edit a Joomla article, it is desirable to have the highest possible height of the editor. So, what is the global setting of the editor plugin good for? It does not really help us. 
Further more, the height of the textarea element in the forms should not be too different from the WYSIWYG editor height, otherwise the content on the page will jump too much if someone uses 'Toogle editor'. I don't like that very much 😉 .

So if we want to limit the height of the WYSIWYG editor, in my opinion the JoomGallery should have the last word about the height, the height of the textarea elements should be about the same. Otherwise we can leave it in my opinion.

**Comment by 19leunam93** [comment]
> in my opinion the JoomGallery should have the last word about the height

Yes, I support that.

Administrators will probably set the dimensions of the editors, in order to optimise the editor for joomla articles (com_content), if they ever adjust the editor. Most admins will simply leave it at standard and not even notice, if JoomGallery would overwrite the height.

The description of an image or image-category is mostly not very long. Therefore small editor dimensions are preferrable for having neat JoomGallery forms.

**Comment by MrMusic** [comment]
Thank you for the updates.

>Further more, the height of the textarea element in the forms should not be too different from the WYSIWYG editor height, otherwise the content on the page will jump too much if someone uses 'Toogle editor'. I don't like that very much 😉 .

This jumping comes probably by hiding the buttons. Unfortunately, this effect already exists in the current Joomla/JoomGallery.

When using the 'CodeMirror' editor, the isis template sets a 'min-height' of 400px. I think this value should be overwritten in the admin.joomgallery.css.
Otherwise, we can leave it that way.

**Comment by Erftralle** [comment]
Unfortunately I found another small glitch. When toggeling the editor to fullscreen the editor is now still restricted to max-height. I was able to solve that problem for TinyMCE by changing the CSS to

```
[id*="form"] .js-editor-tinymce > .mce-container:not(.mce-fullscreen) iframe {
  max-height: 150px;
}
```

Maybe there is a more elegant way?

There should be similiar solutions possible for the other editors.

**Comment by Erftralle** [comment]
Thank you for the additions.

I have tested this item ✅ successfully with "No editor", "CodeMirror" and "TinyMCE".

@MrMusic: Are you satisfied with the solution, could you please test the remaining editors?

**Comment by MrMusic** [comment]
>@MrMusic: Are you satisfied with the solution, could you please test the remaining editors?

I do an additional test with JCE Editor.
[CKEditor](https://extensions.joomla.org/extension/ckeditor/) is outdated and does not work anymore.
I have tested this item ✅ successfully. Thank you.

**Comment by 19leunam93** [comment]
> CKEditor is outdated and does not work anymore.
But Dropeditor is based on CKEditor and one of my favorite editors. Thats why I support also cke editors...

**Comment by MrMusic** [comment]
>But Dropeditor is based on CKEditor and one of my favorite editors. Thats why I support also cke editors...

Then you have Dropeditor already tested and we can merge it...

**Comment by 19leunam93** [comment]
Yes, I have tested this item ✅ successfully with "No editor", "CodeMirror", "TinyMCE", "Dropeditor", "JCE" and "CKEditor" (even this Editor is very buggy, the height limitation works).

**Pull request merged**
