### PR TITLE
Add missing permission check

### PR DESCRIPTION
**Pull request by MrMusic**
This is a possible fix for https://github.com/JoomGalleryfriends/JoomGallery/issues/62

It adds a check on the permissions when moving images in image manager.

Should messages about missing permissions be output as notice, warning or error?
Further information on checking the permissions for recreate and rotate is also welcome.

### CODE REVIEW

**Comment by Erftralle** [comment]
> It adds a check on the permissions when moving images in image manager.

Shouldn't the rights to "joom.upload.inown" also be considered in the query? 

> Should messages about missing permissions be output as notice, warning or error?

In my opinion it should be a warning.

> Further information on checking the permissions for recreate and rotate is also welcome.

I think at least there should be a check on the rights "core.edit" and core.edit.own. But this should be treated in separate issues or pull requests. Maybe there are more opinions to that point.

**Comment by MrMusic** [comment]
>Shouldn't the rights to "joom.upload.inown" also be considered in the query?

Thanks for the hint. I added a check for this. 
Maybe the code style still can to be improved?

>I think at least there should be a check on the rights "core.edit" and core.edit.own. But this should be treated in separate issues or pull requests. 

Ok, agreed.

**Comment by Erftralle** [comment]
> I added a check for this.

Thank you very much, this is working.

> Maybe the code style still can to be improved?

In fact the readability could be improved 😉 . Regarding to the code style the **indentation** should be like
```
      // Check whether we are allowed to move to target category
      if(  (   !$user->authorise('joom.upload', _JOOM_OPTION.'.category.'.$catid)
            && (   !$user->authorise('joom.upload.inown', _JOOM_OPTION.'.category.'.$catid)
                || !$category->owner
                || $category->owner != $user->get('id')
               )
           )
         // Check whether we are allowed to move the image
         || (   !$user->authorise('core.edit', _JOOM_OPTION.'.image.'.$id)
             && (   !$user->authorise('core.edit.own', _JOOM_OPTION.'.image.'.$id)
                 || !$row->owner
                 || $row->owner != $user->get('id')
                )
           )
        )
      {
        $unaffected_images++;
        continue;
      }
``` 
In my opinion, you can "see" and understand the logical connection better this way.

In order to show the warning as warning I would change line 649 to
```
      JFactory::getApplication()->enqueueMessage(JText::plural('COM_JOOMGALLERY_IMGMAN_ERROR_MOVE_NOT_PERMITTED', $unaffected_images), 'warning');
```

`JError::raiseWarning()` in fact does not show a warning but an error, either a bug or I have missed something?

**Comment by MrMusic** [comment]
@Erftralle: Thank your for the hints.
It seems JError::raiseWarning() does not work as expected for me.
It is now implemented as recommended.

**Comment by Erftralle** [comment]
I have tested this item ✅ successfully. Thank you very much.

**Pull request merged**
