### PR TITLE
Improved user panel view (mobile)

### PR DESCRIPTION
**Pull request by 19leunam93**
This pullrequest is built on top of #25. Additionally to #25 it improves the user panel (frontend view) for mobile devices.

| Before (#25) | After (#26) | 
|------ |------ |
|  | Screenshot_20191203-093757 |

### CODE REVIEW

**Comment by MrMusic** [comment]
I'm not sure if all changes in admin.joomgallery.css are so intentional.
Otherwise, it works when using a bootstrap template.

In my test, I noticed that on Phones no selection of the category is possible.
In my opinion, the selection of the category is so important that it should be enabled on phones.

**Comment by 19leunam93** [comment]
> I'm not sure if all changes in admin.joomgallery.css are so intentional.
No, they are changes, which comes from #25.

> In my test, I noticed that on Phones no selection of the category is possible.
Yes, but hiding the categories was not a change of mine. But phones does have limited display space and therefore I support hiding the categories. Mobile phones are anyway not a good choice for administration work...

**Comment by 19leunam93** [comment]
I think we can merge this. It is for sure not an optimal solution for mobile, but it is better as before and the best we can do with minimal effort. Better results we can achieve with BootOne.

I don't want this request to stop the release of v3.4.0. So if you don't want to merge it now, close it and I will commit it again later...

**Comment by 19leunam93** [comment]
I successfully tested ✅ this item on an android phone (720x1280px) with firefox browser

**Comment by MrMusic** [comment]
I have tested this item ✅ successfully.
Thank you.

**Pull request merged**
