### PR TITLE
Configuration reset to default

### PR DESCRIPTION
**Pull request by MrMusic**
This is a redo of https://github.com/JoomGallery/JoomGallery/pull/106.

Thanks to @Erftralle for help with this feature.

Small problem: When running 'reset configuration' there is a php Notice:
PHP Notice:  Undefined property: JoomAdminConfig::$id in ...administrator\components\com_joomgallery\helpers\adminconfig.php on line 1009, referer: ...administrator/index.php?option=com_joomgallery&controller=config
I don't know where the $this->id value is set?

### CODE REVIEW

**Comment by Erftralle** [comment]
> Small problem: ....

Seems that you have found an old bug.
It should be `$this->_id` instead of `$this->id` in the line you referenced.
What do you think?

**Comment by MrMusic** [comment]
>It should be $this->_id instead of $this->id in the line you referenced.

Thanks for the tip.
Yes, the php notice disappears.

Unfortunately, when using the advanced configuration manager then the saving of the joom_settingsxx.css for the additional config lines does not work anymore.
When use $this->id, the saving of the additional joom_settingsxx.css files works fine.

**Comment by Erftralle** [comment]
Ok, I see.

Change the referenced line to

`
    $css_settings_file = JPATH_ROOT.'/media/joomgallery/css/'.$this->getStyleSheetName(isset($this->id) ? $this->id : 0);
`

That works for me.

**Comment by MrMusic** [comment]
>Change the referenced line to
>
>$css_settings_file = JPATH_ROOT.'/media/joomgallery/css/'.$this->getStyleSheetName(isset($this->id) ? $this->id : 0);

Works great. Thank you very much.

**Comment by Erftralle** [comment]
Nearly perfect. Thank you.

Unfortunately, when resolving the merge conflicts, you forgot to insert the parameter  `jg_storenametagip` into the file **_setdefault.install.mysql.utf8.sql_**.

**Comment by MrMusic** [comment]
>Unfortunately, when resolving the merge conflicts, you forgot to insert the parameter jg_storenametagip into the file setdefault.install.mysql.utf8.sql.

Thank you for the hint.
I hope now it is complete :smiley:

**Comment by Erftralle** [comment]
> I hope now it is complete :smiley:

I hope so too :wink: !

I have tested this item :white_check_mark: successfully.

Thank you.

**Pull request merged**
