### PR TITLE
Plugin events (new and modified)

### PR DESCRIPTION
**Pull request by Elfangor93**
During my work with the JoomGallery I missed some Plugin events.
Especially for actions performed in the images list view (change state, recreate, rotate) I would like to have additional event triggers. During the upload process I miss some information in the onJoomBeforeUpload, in order to know which image will be uploaded after the event.

### CODE REVIEW

**Comment by Elfangor93** [comment]
The "onJoomAfterPrepareDisplayHTML" event in JoomGalleryViewDetail and JoomGalleryViewCategory are ment to grab additional, raw item data to current item (category or image) which are not formatted. To be used in custom layouts or template overrides.

**Comment by MrMusic** [comment]
Thank you for this pull request.
I don't understand exactly what the event "onJoomAfterPrepareDisplayHTML" can be used for. But shouldn't this event also be included in the toplists and search views?
Since the changes probably will not affect backward compatibility, I would be for merge this PR.

**Comment by Elfangor93** [comment]
Some information is tranfered into HTML code already inside the view.html.php. Therefore in the template file you can get this information only as HTML code. But if you would like to have this information structured in a different way (for example if you use another css framework in your template) it is very complicated to modify the HTML code string to your needs.

Or another usecase - you need some addition information which is not available at the moment inside the template file. You could grab this information directly inside your template file by reading it out of the database (using JDatabase) for example. I dont like this. I like to have a clean template file with only HTML relevant code. So I could use the plugin event to grab the information inside the plugin and attach it as raw data to `$this->item` which I can address in my template file.

This Plugin event allows you to add raw data directly to the item object which you can access in the template file using `$this->item->yourCustomData`.

Inside the detail view, `$this->item` would be `$this-image` and in the category view it would be `$this-category`

**Comment by Elfangor93** [comment]
_shouldn't this event also be included in the toplists and search views?_

It could be included in favourites, search and toplist view too...
For my part, I do not need any further information in these views. Actually, I remove all available information from these views. I use them only as listings of image-titles with a link to its detail views. Therefore i do not need any additional information in these views.

But if you like, I could add the event there too.
In your opinion, to which "item" object you want to attach the additional information in these views?

**Comment by Elfangor93** [comment]
I have tested this item ✅ successfully.

**Comment by MrMusic** [comment]
I have tested this item ✅ successfully.

**Comment by Erftralle** [comment]
This pull request shouldn't have been merged to the master branch because it only contains new features and no bug fixes. It doesn't even have a milestone yet.

Correct me if I am wrong or if you changed the version strategy, but only bug fixes should be merged directly into the master branch so that a new bug fix release (next would be 3.5.1) without new features can be released quickly if necessary (in case of a serious bug or safety fix).

Now the next release must be a new feature release (next would be 3.6.0).

To my opinion the merge of this pull request should be reverted and than targeted to the 3.6.0 branch.

But that is just my opinion.

**Comment by MrMusic** [comment]
>...or if you changed the version strategy...

The version strategy was not changed.
Yes, you are right, maybe I should have paid more attention to that.
New functions should actually be integrated into the next feature release (next: 3.6.0).
The distinction between 'new feature' or not in the case of minor changes is sometimes a little difficult.

**Comment by Erftralle** [comment]
> The distinction between 'new feature' or not in the case of minor changes is sometimes a little difficult.

It's not that difficult 😉. Only **bug fixes** and **security fixes** should go into the next **bug fix release** (next would be 3.5.1) and only pull request containing bug fixes should be merged directly to the master branch. The reason for that I mentioned above.

Since this pull request does not contain any bug fix it should go to the next feature release (next would be 3.6.0).

**Comment by Elfangor93** [comment]
I dont care if the changes of this PR are released with v3.5.1 or v3.6.0. I just hear the first time about the version strategy and how to apply that regarding target branch of a PR.

Maybe we should update the Readme with all the important informations contributors should now and care about.

**Comment by Erftralle** [comment]
> This is the first time I've heard about versioning strategy and how to apply it to the target branch of a PR.

It's not that different from Joomla! itself does it (see [here](https://docs.joomla.org/Version_Strategy)). The last valid version strategy of JoomGallery can be found [here](https://web.archive.org/web/20200922215616/http://en.joomgallery.net/faq/general-faq/versioning.html). Joomla! itself allows small improvements and limited new functions with full backward compatibility with previous maintenance steps. But what exactly is **small** and **limited**. That's why I prefer the way how JoomGallery did it.

But everything can be a matter of change, that's why I asked whether the versioning strategy has been changed.

> Perhaps we should update the readme with any critical information that contributors should be now and important.

That's a good idea. Maybe one ore more articles about bounties, contributing, versioning, code style etc. on JoomGalleryfriends that can be linked from here?

**Pull request merged**
