### PR TITLE
External search engines integration

### PR DESCRIPTION
**Pull request by Elfangor93**
This PR integrates external search engines into JoomGallery. External search engines needs to have a Plugin of group="joomgallery" and the plugin events "onJoomSearchEngineGetName" and "onJoomSearch".
A configuration option is added to the configuration manager. The option is found in the search tab. Any external search engine which has a JoomGallery-Plugin installed and enabled will be listed there in the config manager. There you can select which search engine you want to use to create the search view.
The serach form field in the header of JoomGallery will generate the search view based on the selected search engine.

### Prerequirements
- PR #78 (More plugin events)
- A suitable search plugin (e.g https://github.com/JoomGalleryfriends/JoomFinderPlugin)

### Info
Since this PR depends on the PR #78 I will do a rebase as soon as the PR #78 is merged and change this PR from 'Draft' to 'Ready for review'.

### CODE REVIEW

**Comment by Elfangor93** [comment]
Rebased with v3.6.0...

**Comment by MrMusic** [comment]
Sometimes the search result are wrong

Steps to reproduce the issue

Install last JoomFinder package 
Set SmartSearch as search engine in JoomGallery Configuration Manager
Go to Component -> Smart Search -> Options: Set 'Allow Empty Search' to Yes
Enter a wrong search term in JoomGallery component search box, example: 'xxx'

Expected result
Search result: There were no images found that match the search pattern!

Actual result
All images are found/shown

Hint: When using Joomla Smart Search component the search result is correct (No Results Found)

System information
Joomla 3.10.6
PHP 8.0.10

**Comment by Elfangor93** [comment]
I can confirm this issue.
But the issue is created in the Smart Search component (com_finder) not in this plugin.

Steps to reproduce the issue in smart search:
- Install last JoomFinder package
- Go to Component -> Smart Search -> Options: Set 'Allow Empty Search' to Yes
- Go to Component -> Smart Search -> Press "Index" button to start first indexing of content
- Enter a wrong search term in the smart search by applying the filter "Search by Type" = "Image (JoomGallery)"

This is what the JoomGallery-Search is performing in the back when searching for a specific term in the gallery search field. The plugin is performing a smart search with the applied filer "Search by Type" = "Image (JoomGallery)".

Therefore, to solve this issue the corresponding issue in com_finder has to be solved...

**Comment by MrMusic** [comment]
>Therefore, to solve this issue the corresponding issue in com_finder has to be solved...

Ok, if it's not a bug in the finder plugin there's probably nothing you can do here...

I have tested this item ✅ successfully. Thank you very much.

**Pull request merged**
