### PR TITLE
Add support for basic WebP images

### PR DESCRIPTION
**Pull request by MrMusic**
This PR adds the support for WebP images.

WebP is a modern image format which is supported by almost all browsers. See
https://en.wikipedia.org/wiki/WebP 
https://caniuse.com/webp

ImageMagick and GD2 library supports the WebP format.

WebP supports transparency, animation and metadata

This Works:
Upload/handle WebP images with or without transparency

The following does **not** work:
- Calculation of needed memory in JoomIMGtools:calculateMemory, the current values are simply dummies.

- WebP with Animation
No upload possible. Perhaps changes are still required in other files? a 'webpframecreator' in JoomIMGtools?

- Metadata
I have no idea how to read and save metadata (Exif?) from WebP.
A WebP image with metadata i could not find either.

See 'Todo' in changed files.

Maybe someone has an idea how to solve the problems?

### CODE REVIEW

**Comment by Elfangor93** [comment]
>I have no idea how to read and save metadata (Exif?) from WebP.

JoomGallery currently is only able to read metadata for JPG files even PNG files do also support metada. I think we can skip the functionality of reading metadata from WebP files as well.

But JG is currently able to copy available metadata from source to destination file during image maipulation. This is for example needed when rotate an image based on metadata. The rotated image will loose the metadata by default and needs to be added after manipulation again. This we currently can do for JPG and PNG files. (GIF does not support metadata at all).

If we need metadata support then I guess copy the metadata is the only thing needed...

**Comment by Elfangor93** [comment]
> Calculation of needed memory in JoomIMGtools:calculateMemory

This is a very time consuming process. When I did it for the other file formats I captured the memory uasges for a lot of different images and tried to fit the following equation to the measured values.

`$memoryUsage = round(( ((($bits * $channels) / 8) * $src_pixel * $tweakfactor + (($bits * $channels) / 8) * $dst_pixel * $tweakfactor) * pow($frames, 1.02) + 2 * 1048576) * 1.08)`

where

`$tweakfactor = ($m * $src_pixel) + $c`

Therefore the fitting parameters are:
- $m
- $c

These are the other variables:
- $src_pixel number of pixels of the source image
- $dst_pixel number of pixels of the destination image
- $frames number of frames
- $channels number of channels per pixel
- $bits number of bits per channel

**Comment by Elfangor93** [comment]
> WebP with Animation

Maybe we could use code from here:
https://github.com/aloMalbarez/php-GD-Animated-webp

**Comment by MrMusic** [comment]
Thanks for your answer.

>But JG is currently able to copy available metadata from source to destination file during image manipulation

This is what I meant.

It seems there is no easy way to process animated WebP images with gdlib: https://github.com/libgd/libgd/issues/648
I think we should leave it then with the support of basic WebP images without animation.
Maybe someone has the possibility to improve this for JoomGallery 4.

**Comment by Elfangor93** [comment]
@MrMusic I will perform the tests, when you have reacted on my code reviews...

**Comment by Elfangor93** [comment]
Would be nice, if we cold get an information that animated webp files are not supported.
image

**Comment by MrMusic** [comment]
>Would be nice, if we cold get an information that animated webp files are not supported.

There is now an new error message.

**Comment by Elfangor93** [comment]
Bug found when dynamically add watermarks to webp file...

### Steps to reproduce the issue

- Choose whatever image processor you want (GD or IM)
- Upload a webp image
- Set in config manager, Dynamic adjustments >> Add watermark?? to Yes
- Switch to the frontend and visit the detail view of the webp image

### Expected result
Image is displayed with watermark applied.

### Actual result
image

### System information
PHP-Version: 7.4.29
Database: 5.5.5-10.4.24-MariaDB
Joomla: 3.10.10
ImageMagick: 7.1.0-41 Q16 x64

**Comment by MrMusic** [comment]
Thanks for the hint. 
Should be fixed with last commit.

**Comment by Elfangor93** [comment]
I have tested this item ✅ successfully. Thank you very much.

**Comment by Elfangor93** [comment]
It works now, when ImageMagick is used as image processor. With GD we dont get any image when watermarking is activated.
image

The response code is 200, but the image is not there:
image

**Comment by MrMusic** [comment]
That is strange.
I have never had any problems with GD and WebP.
Apart from locally on my computer, I have also tested it on two other hosting provider: No problems when GD is set as image processor.
One hoster doesn't support WebP in imagemagick. So it can't work there with imagemagick.
Have you checked in the 'system information' whether WebP support is activated in GD?

**Comment by Elfangor93** [comment]
This problem accurs for me only for the watermarking. Everything else works fine with GD and webp.
At the moment I can not take a deeper look into the problem, since I am in holiday without my development machine.

**Comment by MrMusic** [comment]
For testing i have created a website and uploaded WebP images here: http://mrmusic63.de/webp

**Comment by Elfangor93** [comment]
I tested visiting the detail view of a webp image with dynamic watermark activated with different PHP versions:

- 5.6.4: not working
- 7.3.5: working
- 7.4.16: working
- 7.4.27: not working
- 8.0.3: working
- 8.0.15: not working
- 8.1.2: PHP errors

The system is exactly the same except the PHP version was changed. WEBP Support is enabled in all PHP versions.

grafik

**Comment by MrMusic** [comment]
Has anyone else tested this pull request?
Were there any problems?
For me it works fine with all current PHP versions.... :-)

**Comment by szepty-ziemi** [comment]
@MrMusic and @Elfangor93 I will be happy to help to test this PR. Could you provide Acceptance Criteria or at least what to test?
Testing is required for both Linux and Windows?

**Comment by Elfangor93** [comment]
This is what I tested:

Uploading
-- three different WebP images
-- GD and IM (Image processors)
-- All available upload methods
-- Frontend and Backend upload
-- Different resizing settings (only spot tests)

Displaying
-- Thumbs (Backend: Image Manager, Frontend: Category view)
-- Detail (Backend: Edit image, Frontend: Detail view)
-- Original (Frontend: Popup)
-- Thumbs with dynamic cropping
-- Details with dynamic watermarking

**Comment by Elfangor93** [comment]
This is what I tested:

Uploading
-- three different WebP images
-- GD and IM (Image processors)
-- All available upload methods
-- Frontend and Backend upload
-- Different resizing settings (only spot tests)

Displaying
-- Thumbs (Backend: Image Manager, Frontend: Category view)
-- Detail (Backend: Edit image, Frontend: Detail view)
-- Original (Frontend: Popup)
-- Thumbs with dynamic cropping
-- Details with dynamic watermarking

Acceptance Criteria
- No PHPor Joomla errors
- No PHP warnings
- Behavior as expected

**Comment by szepty-ziemi** [comment]
ENV: https://prnt.sc/rzaMPBDSHE7_

Notices displayed in JoomGallery Open Bounties (JoomGallery Dashboard)

obraz

obraz

**Comment by szepty-ziemi** [comment]
When trying to upload animated webp we get an error message... but the only way to move from this screen is to do a step back in browser:

obraz

A back button or automatic redirection to upload page with error notification would be nice solution.

**Comment by szepty-ziemi** [comment]
GD Library / When enabling Add watermark images are not displayed in the frontend:

obraz

No detail image and original images are displayed:

obraz

When disable Watermark image is back:

obraz

**Comment by szepty-ziemi** [comment]
GD (didn't tested Java Upload - check comment | Issue with watermarking - linked comment)

ENV: https://prnt.sc/alA1S6RXbjMz

Uploading
-- ✓ three different WebP images
-- ? All available upload methods **(Firefox no longer provides NPAPI support (technology required for Java applets)**
-- ✓ Frontend and Backend upload
-- ✓ Different resizing settings (only spot tests)

Displaying
-- ✓ Thumbs (Backend: Image Manager, Frontend: Category view)
-- ✓ Detail (Backend: Edit image, Frontend: Detail view)
-- ✓ Original (Frontend: Popup)
-- ✓ Thumbs with dynamic cropping
-- X Details with dynamic watermarking https://github.com/JoomGalleryfriends/JoomGallery/pull/102#issuecomment-1212481485

**Comment by szepty-ziemi** [comment]
Side note: ImageMagick correctly process animated WEBP files :) 

http://siristru.prolusatia.pl/galeria/test-webp/xxxxx-3-47.html

**Comment by szepty-ziemi** [comment]
IM

Uploading
-- ✓ three different WebP images
-- ? All available upload methods (Firefox no longer provides NPAPI support (technology required for Java applets)
-- ✓ Frontend and Backend upload
-- ✓ Different resizing settings (only spot tests)

Displaying
-- ✓ Thumbs (Backend: Image Manager, Frontend: Category view)
-- ✓ Detail (Backend: Edit image, Frontend: Detail view)
-- ✓ Original (Frontend: Popup)
-- ✓ Thumbs with dynamic cropping
-- ✓ Details with dynamic watermarking

**Comment by MrMusic** [comment]
@szepty-ziemi Thank you very much for testing. We are very grateful for this.

>When trying to upload animated webp we get an error message... 

Processing animated WebP images is very difficult and not supported by this pull request, only 'static images' or with transparency.
See discussion in the posts above. 


>...but the only way to move from this screen is to do a step back in browser:
>On frontend we have buttons that will take us from this page. I think we need something similar in backend:

Yes, I can confirm that. This should be changed in another pull request.

The problem with an activated watermark probably lies in the watermark file itself.
Because it is an 'interlaced' PNG file, some PHP/GD versions generate (falsely) a warning message that prevents the image from being displayed. Attached is a new watermark file that is 'not interlaced'. I hope this fix the problem.

**Comment by szepty-ziemi** [comment]
@MrMusic danke :) I confirm that alternative watermark file works perfectly, no issue with GD and watermarking now.

**Comment by Elfangor93** [comment]
I have tested this item ✅ successfully. Thank you very much.

**Comment by reilldesign** [comment]
**System Information**
 
PHP Built On | Linux localhost 3.10.0-1160.36.2.el7.x86_64 #1 SMP
Database Type | mysql
Database Version | 5.7.38-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.4.30
Web Server | Apache/2.4.54 (Unix)
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.10.10 Stable [ Daraja ] 18-June-2022 16:32 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:91.0) Gecko/20100101 Firefox/91.0


**Uploading**
-- three different WebP images: Different sizes and qualities (lossless, lossy)
-- GD and IM (Image processors)
-* All available upload methods: Drag & Drop, File Input Upload, FTP Upload
-- Frontend and Backend upload
-- Different resizing settings (only spot tests)

**Displaying**
-- Thumbs (Backend: Image Manager, Frontend: Category view)
-- Detail (Backend: Edit image, Frontend: Detail view)
-- Original (Frontend: Popup)
-- Thumbs with dynamic cropping
-- Details with dynamic watermarking (custom png watermark)

**Acceptance Criteria**
-- No PHP or Joomla Errors
-- No PHP warnings
-- Behavior as expected


I have tested this item ✅ successfully

**Comment by MrMusic** [comment]
Thanks to all testers for their help.

**Pull request merged**
