### PR TITLE
Replace with metadata - V2

### PR DESCRIPTION
**Pull request by 19leunam93**
replaces the other pull request with name: Replace with metadata #12

### CODE REVIEW

**Comment by 19leunam93** [comment]
What is about the german language files - where do I have to commit these?

Maybe these si the need of defining some default values for the ReplaceWithMetadata-Settings. But I didn't know where to do that...

**Comment by MrMusic** [comment]
>What is about the german language files - where do I have to commit these?

Here on Github there are only the English language files. The German language files are edited by the team itself. When a new version is released, it will be updated on the website.

>Maybe these si the need of defining some default values for the ReplaceWithMetadata-Settings. But I didn't know where to do that...

The default settings for the Configuration Manager are set in the file setdefault.install.mysql.utf8.sql. This file is currently missing in this Pull Request.
The new configuration options should also be entered in the file administrator/components/com_joomgallery/helpers/config.php.

Otherwise, the following notes:

1. Consider adding the Replace with Metadata settings to the 'Replacements' tab in Configuration Manager instead of creating a new tab?

2. Warnings are displayed after the end of the ftp upload, even if the warnings are switched off in the Configuration Manager.

3. If the upload takes longer, warnings will be lost due to the 'Refresh'.

**Comment by 19leunam93** [comment]
> Consider adding the Replace with Metadata settings to the 'Replacements' tab in Configuration Manager instead of creating a new tab?
I would not do that, because there are a lot of settings for the 'Replace with Metadata'. In my optinion it would be overcrowded and confusing if these setting will be in the 'Replacements' Tab as well. Maybe we could thing about a renaming of these two tabs to reduce confusion?

> If the upload takes longer, warnings will be lost due to the 'Refresh'.
Which upload methods are suffering from the 'Refresh'? In my test environment I am not able to force a refresh even for extremly long uploading times. Thats why I was not able to test that by myself. But I am treating now the variable $_warningoutput in the whole upload.php the same way as the $_debugoutput variable. So there should be the same behavior for both variables.

**Comment by MrMusic** [comment]
>Which upload methods are suffering from the 'Refresh'? In my test environment I am not able to force a refresh even for extremly long uploading times. Thats why I was not able to test that by myself. 

I test it with the ftp upload in a local xampp installation: 
php.ini with max_execution_time=15. 
Upload of about 100 images.
Then after about 12 seconds, a refresh occurs.

I believe one problem is on line 1317. If I do not 'comment out' this line all warnings be displayed after upload.
Nevertheless, the problem remains that after the upload warnings are displayed although warnings are disabled in the JoomGallery configuration.

**Comment by 19leunam93** [comment]
> I believe one problem is on line 1317. If I do not 'comment out' this line all warnings be displayed after upload.

You are ringt uncommenting this line and JoomGallery keeps all the warnings. By the way JoomGallery also forgets the debugoutput by default (line 1316 is alo commented out)!

Is line 1316 commented out, in order to forget $_debugoutput on refresh by purpose? Wouldn't it be smart to treat $_warningoutput the same way and let JoomGallery forget the warnings on refresh too?

With line 1317 uncommented I get a huge list of warnings at the end of uploading which no one will ever read! In my opinion we should line 1317 keep commented out. Or on the other hand also umcomment line 1316, so that debugoutput ans warningoutput is treated the same way...

What do you mean?

**Comment by MrMusic** [comment]
>Is line 1316 commented out, in order to forget $_debugoutput on refresh by purpose? Wouldn't it be smart to treat $_warningoutput the same way and let JoomGallery forget the warnings on refresh too?

I do not understand why line 1316 is commented out.
In my opinion, it is a bug.


>With line 1317 uncommented I get a huge list of warnings at the end of uploading which no one will ever read! In my opinion we should line 1317 keep commented out. Or on the other hand also umcomment line 1316, so that debugoutput ans warningoutput is treated the same way...

When I activate the debug as an admin (like the warnings in the configuration manager) I also expect that 'all' warnings/debug hints will be displayed.
If a part of it is forgotten (for whatever reason) that is in my opinion a bug.
Whether only a few or many images are uploaded may not matter. 
Finally, it is the decision of the admins if he wants to see (all) the warnings/debug hints or not.

Maybe there are other opinions?

**Comment by 19leunam93** [comment]
> Finally, it is the decision of the admins if he wants to see (all) the warnings/debug hints or not.

Makes sense to me. So I will uncomment line 1316 & 1317 in the uploadFTP routine as well as the same two lines in the uploadBatch routine. Therefore no infos (debug/warnings) will be forgotten anymore during refresh.

**Comment by MrMusic** [comment]
Thank you very much. 
For me it looks good now.


>Maybe we could think about renaming of these two tabs to reduce confusion?

Does somebody has any idea?

**Comment by 19leunam93** [comment]
> Maybe we could think about renaming of these two tabs to reduce confusion?

My Suggestion:
Rename Tab "Replacements" to "Special characters" and "Replace with meta data" to "Use image metadata"

**Comment by 19leunam93** [comment]
With the lastest changes I have the problem, that the language strings of the IPTC and EXIF property-names are not rendered properly even the language files containing this language strings are loaded correctly...

grafik

The language files are loaded in the JoomGalleryView-Class (/components/com_joomgallery/view.php) on line 104 for the frontend and (administrator/components/com_joomgallery/view.php) on line 93 for the backend respectively.
Does anyone knows why the language strings arent rendered correctly?

**Comment by 19leunam93** [comment]
The last few commits are improvements based on feedbacks from @MrMusic and @Erftralle.
Ready to merge?

**Comment by Erftralle** [comment]
Thank you for your contribution.

I've created a pull request on your branch that has a few suggestions with improvements, tweaks, and code style changes. You can see at each commit of the pull request what I did exactly.

**Comment by 19leunam93** [comment]
Thank you for the code-cosmetics. I think the changes are good.

**Comment by Erftralle** [comment]
Thank you for merging my code proposals.

Describing all of my code changes as "code cosmetics" is, in my opinion, not only wrong, but also provocative and arrogant. But maybe we just have a different view of "Code Cosmetics". Perhaps your definition includes bug fixes and performance optimizations, as well as simplifications to improve readability and the compliance to a consistent code style?

**Comment by 19leunam93** [comment]
If my rash formulation upset you, I do apologise. That wasn't my intention.
Of course, I appreciate your proposals - thanks for taking the time to improve my code suggestion...

**Comment by Erftralle** [comment]
Apology accepted.

I have tested this item ✅ successfully. I think it's ready to merge now.

**Comment by MrMusic** [comment]
Sorry for my late answer.
Thank you very much @19leunam93 and @Erftralle!
In my test, everything worked well, with one exception: the 'Exif comment' is not taken. The problem seems to be related to the php function 'exif_read_data'. It returns the comment in a separate 'section', not in the 'Exif' section, see https://www.php.net/manual/en/function.exif-read-data.php.
I will create a pull request for this.

**Comment by Erftralle** [comment]
Thank you @MrMusic. Always good to have an extra test. 

I did another extra test too, I edited an image with ExifPilot and added a 'UserComment' to it.
A variable dump of the return of readMetaData() during the upload showed me

```
array (size=2)
  0 => 
    array (size=16)
      'FileName' => string 'jg34_1_20191107_2094592802.jpg' (length=30)
      'FileDateTime' => int 1573134898
      'FileSize' => int 351485
      'FileType' => int 2
      'MimeType' => string 'image/jpeg' (length=10)
      'SectionsFound' => string 'ANY_TAG, IFD0, THUMBNAIL, EXIF' (length=30)
      'COMPUTED' => 
        array (size=9)
          'html' => string 'width="1800" height="1200"' (length=26)
          'Height' => int 1200
          'Width' => int 1800
          'IsColor' => int 1
          'ByteOrderMotorola' => int 1
          'UserComment' => string 'A comment from the EXIF data.' (length=29)
          'UserCommentEncoding' => string 'ASCII' (length=5)
          'Thumbnail.FileType' => int 2
          'Thumbnail.MimeType' => string 'image/jpeg' (length=10)
      'Orientation' => int 1
      'XResolution' => string '72/1' (length=4)
      'YResolution' => string '72/1' (length=4)
      'ResolutionUnit' => int 2
      'DateTime' => string '2001:12:30 00:00:00' (length=19)
      'YCbCrPositioning' => int 1
      'Exif_IFD_Pointer' => int 134
      'THUMBNAIL' => 
        array (size=3)
          'Compression' => int 6
          'JPEGInterchangeFormat' => int 232
          'JPEGInterchangeFormatLength' => int 3958
      'UserComment' => string 'ASCII���A comment from the EXIF data.' (length=37)
  1 => 
    array (size=3)
      '1#090' => 
        array (size=1)
          0 => string '%G' (length=3)
      '1#000' => 
        array (size=1)
          0 => string '�' (length=2)
      '2#055' => 
        array (size=1)
          0 => string '20001030' (length=8)
```
and the image description (I chose to use 'UserComment' for my image description) was set to

**ASCII**A comment from the EXIF data.

Not the same behaviour than you described but also not correct because of the leading 'ASCII'.
There is another 'UserComment' in the subarray 'COMPUTED' without the leading 'ASCII'.

**Pull request merged**
