### PR TITLE
Allow unsafe zip upload

### PR DESCRIPTION
**Pull request by MrMusic**
There are problems with the zip upload since Joomla increased the security checks.
See also https://github.com/JoomGallery/JoomGallery/issues/66 and https://www.forum.joomgalleryfriends.net/forum/index.php?thread/58-batch-upload-error-archive-does-not-exist/
This PR adds a option in Configuration Manager to disable the security checks.

### CODE REVIEW

**Comment by Erftralle** [comment]
Thank you very much.

I have tested this item ✅ successfully.

I've created a pull request towards your branch that fixes a small code style issue and improves the english spelling and grammar.

**Comment by 19leunam93** [comment]
With this pull request users which have access to the joomla backend and the JoomGallery administrator interface but not to the configuration of JoomGallery are not able to switch between safe and unsafe Zip Upload. Depending on what their administrator has set in the configuration manager, they are limited to use safe or unsafe mode.

I am speaking of users with the following permissions:
grafik

I would prefer the user to be able to switch to unsafe upload in the zip-upload form if his administrator allows it (if his administrator chosed yes for unsafe zip upload in the configuartion manager). Switching to the unsafe upload could be done with a check-box in the zip-upload form. The same way as for the debug mode.

**Comment by MrMusic** [comment]
@19leunam93: Thank you for your suggestion. I am not sure if I understood you correctly?
If the administrator allowed the unsafe upload in the configuration manager, should the user additionally have to activate the unsafe upload for each upload? Is that an advantage for the safety?
Actually, the administrator in the configuration manager should decide what is allowed and what is not.
If then with each upload the unsafe upload must be 'activated' again, that the backend users probably only annoying?

**Comment by Erftralle** [comment]
> I would prefer the user to be able to switch to unsafe upload in the zip-upload form if his administrator allows it (if his administrator chosed yes for unsafe zip upload in the configuartion manager). In that case on default they would still use safe mode for zip-upload and only if it does not work they would be able to activate unsafe mode. This could be done with a check-box in the zip-upload form. The same way as for the debug mode.

What would be the work flow, if the first try to upload the zip file would not work (the message is just "No file has been uploaded!")?
**Either** just checking the additional checkbox and trying it again **or** checking the zip file first with other tools to find out that it most probably does not contain any malware and than just checking  the additional checkbox and trying it again (this would be the way I think you would prefer)?

I personally think that in most cases the users would act like described by the first possibility 😉 .

All users with more responsibility will read the warning presented on top of the batch upload form and will act accordingly to ensure that the zip files only contain secure image files 😄 .

**Comment by 19leunam93** [comment]
>If the administrator allowed the unsafe upload in the configuration manager, should the user additionally have to activate the unsafe upload for each upload?

Exactly. In my understanding the unsafe mode is an additional possibility for a user to upload via zip-upload, if it didnt work with the normal mode. In that case the user checks the box for unsafe upload if he is shure, his images are clean and upload it again. All users which want to upload their own taken pictures will check the box without hesitation and without any further checks.
Users which want to upload images from other sources then their own, maybe think and check again if he/she really should upload the pictures.

> the backend users probably only annoying?

No, I don't think so.
In most of the cases the upload works even with the standard mode. If it doesn't the user will be happy to have a possibility to upload his images anyway by just ckeck the box which activates unsave zip upload.

> Actually, the administrator in the configuration manager should decide what is allowed and what is not.

Totally agree. Thats why the checkbox to activate unsafe mode has to be activated by the administrator in the configuration manager.

> All users with more responsibility will read the warning presented on top of the batch upload form

I don't think so. Most of the users will not read anything on top of a form. But the responsible ones will do the checks it if you force them to read the warning. Maybe if an alert-box with the warning appears when checking the checkbox for unsafe mode will do this job?

> the users would act like described by the first possibility

You are definitely right. Most will follow the path of least effort.
But I think with this little hurdles (additional checkbox and alert-box with warning message), we can offer the very useful unsafe mode with a minimum level of safety.
If an administrator doesnt trust his users, he can switch off the mode in the configuration manager completely...

**Comment by MrMusic** [comment]
>All users which want to upload their own taken pictures will check the box without hesitation and without any further checks.
Users which want to upload images from other sources then their own, maybe think and check again if he/she really should upload the pictures.

We should't forget that this option is only for the backend upload, not for the frontend! I think access to the backend should really only get trusted users.

I have now added an additional option in the upload form. Only if this is selected, the unsafe upload is used.
If you think that there must be another warning etc., please post an corresponding code suggestion for the implementation.

**Comment by MrMusic** [comment]
Adding a modal box for activation the unsafe zip upload.
Thanks for the code suggestion to @19leunam93.

**Comment by Erftralle** [comment]
I thought about this pull request once again and would like to fundamentally question the offered solution.

What is the problem? 

The problem is that the function `JFilterInput::isSafeFile()` creates false positives when applied on zip archives. 

In my opinion this function is **absolutely not suitable** to apply on binary zip archives. 

- To inspect the file name for having null bytes or containing forbidden strings in extensions is useless as the archive will be extracted anyway after the check.
- To inspect the binary content for containing invalid tags makes also no sense because the binary file is opened as text file and a found php short tag for instance does not mean that one of the files in the archive really does contain this tag after the archive has been extracted (the files in that archive are compressed that means additionally coded). Nor does it not mean that all files of the archive are free from php short tags if no tag was found in the binary data.

Another point is that this function does not apply any kind of check to the files contained in the zip archive.

So what should we do?

In my opinion we should just disable that useless check on zip files because it either generates false positives and does not prevent the bad things.
Finally Joomla itself processes the zip or generally the archive files in exactly that way by disabling the checks (see com_installer, com_joomlaupdate) namely without any additional hints and warnings.

**Comment by MrMusic** [comment]
>What is the problem?

>The problem is that the function JFilterInput::isSafeFile() creates false positives when applied on zip archives.

Yes I agree with you.
Unfortunately, this function produces many false-positives.

These checks were then built into Joomla! and are enabled by default when calling JFile::upload.

The discussion back then here https://github.com/JoomGallery/JoomGallery/issues/66 I had understood that we should not simply deactivate the security check.
Therefore now the proposal with the option in the configuration manager.
Of course, the best solution would be if the security check in Joomla! would work reliably and there would not be a large number of false positives.

I think @19leunam93 wanted to make the user again explicitly aware of the risks of "unsafe" upload.

>In my opinion we should just disable that useless check on zip files because it either generates false positives and does not prevent the bad things.

The same then for the frontend upload?

**Comment by Erftralle** [comment]
> The discussion back then here JoomGallery#66 I had understood that we should not simply deactivate the security check.

After thinking about it again and studying the code I have **_adapted my opinion_** 😉 .
I now think that it absolutely makes no sense to apply these checks to **binary zip archives** (see my comment above). That's probably the reason why even Joomla does not do it.

> The same then for the frontend upload?

Yes. Just the little change you proposed [here](https://github.com/JoomGallery/JoomGallery/issues/66#issue-115872670).

**Comment by 19leunam93** [comment]
For the sake of completeness:

- This topic was discussed already here joomla/joomla-cms#15563
- And right now there is an actual issue joomla/joomla-cms#26408 which threat the very same issue for the mediamanager

Maybe we could hook up to the discussions at core level to show that various component developers are also confronted with this problem. In my opinion best would be if the joomla core would offer a solution for this problem.

**Comment by MrMusic** [comment]
>Maybe we could hook up to the discussions at core level to show that various component developers are also confronted with this problem. In my opinion best would be if the joomla core would offer a solution for this problem....

The topic is now ancient, I am afraid, there will be no change here. Even if it was the best solution.
At that time, I have taked a look into some components and all have enabled the 'unsafe' upload.
I have now created a new pull request to enable the unsafe zip upload.
If the security check is adjusted in Joomla, we can continue the topic here.

**Comment by Erftralle** [comment]
> If the security check is adjusted in Joomla, we can continue the topic here.

I agree. I close this item for now.

**Pull request closed without merging**
