### PR TITLE
Improved thumbnail display

### PR DESCRIPTION
**Pull request by MrMusic**
This is a redo of https://github.com/JoomGalleryfriends/JoomGallery/pull/17 with a few small changes to the proposal.
Thanks to @reilldesign for the contribution.

### CODE REVIEW

**Comment by 19leunam93** [comment]
I adde a code proposal (https://github.com/MrMusic/JoomGallery/pull/16) to this pull request for a better view of user panel on mobil phones...

**Comment by Erftralle** [comment]
@19leunam93 : 

I think you should open (a) separate pull request(s) for your code proposals because they are not directly related to this topic. If we always add a little more to a pull request it will never be completed and it gets confusing.

@MrMusic :

What do you think of adding 
```
span.hasHint > a {
  display: block;
}
```
to the frontend CSS as it removes the flickering and sometimes not appearing or disappearing of the tooltip when hoovering over the image. It has been added in a similar way by @reilldesign (for the `span.hasTooltip`.)

Additionally I think we could remove the table attribute `width=25` for minithumbimg in 
administrator/components/com_joomgallery/views/control/tmpl/default_notapprovedcomments.php,
administrator/components/com_joomgallery/views/control/tmpl/default_notapprovedimages.php,
administrator/components/com_joomgallery/views/control/tmpl/default_popularimages.php and
administrator/components/com_joomgallery/views/control/tmpl/default_topdownloads.php.

**Comment by MrMusic** [comment]
>What do you think of adding
span.hasHint > a {
  display: block;
}
to the frontend CSS as it removes the flickering and sometimes not appearing or disappearing of the tooltip when hoovering over the image. It has been added in a similar way by @reilldesign (for the span.hasTooltip.)

Done. Thank you for the hint.

>Additionally I think we could remove the table attribute width=25 for minithumbimg...

Done. Thank you for the hint.

**Comment by Erftralle** [comment]
Thank you. I have tested this item ✅ successfully.

**Pull request merged**
